language: python
sudo: false
python:
- 3.4
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
before_script:
- flake8 chatting
script:
- py.test chatting
after_success:
- coveralls
